spring:
  profiles.active: local

azure:
 cosmosdb: 
   uri: https://localhost:8081
   key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
   database: cosmostestdb108

server:
  servlet:
    context-path: /test
  port: 8080

info:
  app:
   name:@project.name@
